version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/code
      - ~/.m2:/root/.m2
    environment:
      - ACCESS_KEY=local
      - SECRET_KEY=local

      - REGION=us-east-1
      - S3_ENDPOINT=http://localstack:4566
      - SQS_ENDPOINT=http://localstack:4566

      - INTEGRATION_ACCESS_KEY
      - INTEGRATION_SECRET_KEY
      - INTEGRATION_TEST_STANDARD_QUEUE_URL
      - INTEGRATION_TEST_S3_BUCKET_NAME

    depends_on:
       - localstack

  localstack:
    image: localstack/localstack:0.12.10
    ports:
      - "4566:4566"
    environment:
      SERVICES:          "sqs,s3"
      # fixes issue https://github.com/localstack/localstack/issues/1485
      HOSTNAME_EXTERNAL: "localstack"

