version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/code
      - ~/.m2:/root/.m2
    environment:
      ACCESS_KEY: "local"
      SECRET_KEY: "local"

      S3_ENDPOINT: "http://localstack:4566"
      SQS_ENDPOINT: "http://localstack:4566"

    depends_on:
       - localstack

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES:          "sqs,s3"
      # fixes issue https://github.com/localstack/localstack/issues/1485
      HOSTNAME_EXTERNAL: "localstack"

