version: 2

jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-clj-sqs-extended-library-wrapper-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-clj-sqs-extended-library-wrapper-

      - setup_remote_docker

      - run:
          name: Install dependencies
          command: docker-compose run --no-deps app lein -U deps

      - run:
          name: Run tests
          command: docker-compose run app sh -c "dev/resources/wait_for.sh localstack:4566 -t 60 -- lein test :all"
          no_output_timeout: 90s

      - store_test_results:
          path: target/test_output

      - save_cache:
          paths:
            - ~/.m2
          key: v1-clj-sqs-extended-library-wrapper-{{ checksum "project.clj" }}

      - deploy:
          name: Publish to Clojars
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                lein deploy releases
            fi

