version: 2

jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-clj-sqs-extended-library-wrapper-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-clj-sqs-extended-library-wrapper-

      - setup_remote_docker

      - run:
          name: Install dependencies
          command: lein -U deps

      - run:
          name: restore mvn repository to remote docker
          command: cd ~/ && tar cf - ./.m2 | ssh remote-docker "cd ~/ && tar xpvf -"

      - run:
          name: Run tests
          command: docker-compose run --name app app sh -c "dev/resources/wait_for.sh localstack:4566 -t 60 -- lein test :all"
          no_output_timeout: 90s

      - run:
          name: Copy test results
          command: docker cp app:/app/target ./

      - store_test_results:
          path: target/test_output

      - save_cache:
          key: v1-clj-sqs-extended-library-wrapper-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

      - deploy:
          name: Publish to Clojars
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                lein deploy releases
            fi

